Only watch Xcode paths from repository contexts (#665)
Fixes the regression

```
ERROR: /Users/asky/.cache/bazel/_bazel_asky/dc58896905f3ead6ad5884ed387b83c5/external/apple_support+/xcode/xcode_configure.bzl:43:25: Traceback (most recent call last):
        File "/Users/asky/.cache/bazel/_bazel_asky/dc58896905f3ead6ad5884ed387b83c5/external/rules_swift+/tools/explicit_modules/extensions.bzl", line 204, column 30, in _sdk_extension_impl
                _generate_local_repos(module_ctx, sdks, exclude_modules)
        File "/Users/asky/.cache/bazel/_bazel_asky/dc58896905f3ead6ad5884ed387b83c5/external/rules_swift+/tools/explicit_modules/extensions.bzl", line 91, column 40, in _generate_local_repos
                toolchains, err = run_xcode_locator(module_ctx, _XCODE_LOCATOR_SRC)
        File "/Users/asky/.cache/bazel/_bazel_asky/dc58896905f3ead6ad5884ed387b83c5/external/apple_support+/xcode/xcode_configure.bzl", line 159, column 25, in run_xcode_locator
                watch_selected_xcode(repository_ctx)
        File "/Users/asky/.cache/bazel/_bazel_asky/dc58896905f3ead6ad5884ed387b83c5/external/apple_support+/xcode/xcode_configure.bzl", line 43, column 25, in watch_selected_xcode
                repository_ctx.watch(selected_path)
Error in watch: attempted to watch path outside workspace, but it's prohibited in the current context
ERROR: error evaluating module extension @@rules_swift+//swift:extensions.bzl%system_sdk
```